@startuml UC003_ForgotPassword_Sequence_Diagram
 title UC003: Quên mật khẩu - Sequence Diagram

actor "Ứng viên, Nhà tuyển dụng" as User
participant "Giao diện quên mật khẩu" as UI
participant "Hệ thống xác thực " as Auth
participant "Cơ sở dữ liệu" as DB
participant "Email" as Mail

User -> UI: 1. Chọn "Quên mật khẩu"
activate UI
User -> UI: 2. Nhập email đã đăng ký
UI -> Auth: 3. Gửi yêu cầu đặt lại mật khẩu
activate Auth
Auth -> DB: 4. Kiểm tra email
activate DB
DB --> Auth: 5. Kết quả kiểm tra

alt Email tồn tại
    Auth -> Mail:  Gửi link đặt lại mật khẩu
    Mail --> User:  Nhận email đặt lại mật khẩu
    User -> UI:  Click link, nhập mật khẩu mới
    UI -> Auth:  Gửi mật khẩu mới
    Auth -> DB:  Cập nhật mật khẩu
    DB --> Auth:  Kết quả cập nhật
    Auth --> UI:  Thông báo thành công
    UI --> User:  Mật khẩu được đặt lại thành công
    note right: Mật khẩu được đặt lại thành công
else Email không tồn tại
    Auth --> UI:  Thông báo lỗi
    UI --> User:  Hiển thị lỗi: Email không tồn tại
    note right: Exception: Email không tồn tại
end



deactivate DB
deactivate Auth
deactivate UI

@enduml